server:
  port: 80
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia%2FShanghai
    username: root
    password: 123456
    # Mei091626.
  redis:
    database: 5
    host: localhost
    password: 123456
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 10
        min-idle: 2
        max-active: 100
        max-wait: 3000
mybatis:
  type-aliases-package: com.zhao.micro.entity
  mapper-locations: classpath:/mapper/*Mapper.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.zhao.micro.entity
  global-config:
    id-type: 0 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    db-column-underline: false

kfphone: 18318484444
upload-path: /home/www/micro/upload
wxpay-notifyurl: zhaolian.natapp1.cc/api/order/callback
order-confirm-url: http://zhaolian.natapp1.cc/order/confirm
auth-redirect-domain: http://zhaolian.natapp1.cc
sms-host: http://localhost:8000/api/sms/send
sms-token: 3216548321671
pay-secret: 9fd27f7cdc952b90191dc5e244266c5d
pay-mchid: 1328938301
gh-appid: wxccdb02024c7de17b
gh-appsecret: 655a51efe37ff9c0feb3ebfd20fd1806
gh-token: stoken
xorpay_aid: 9927
xorpay_appsecret: d46a38f68d90430284e71dcfbe7fad1c